/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BayarSPP;
import javax.swing.JOptionPane;

/**
 *
 * @author sindy
 */
public class SPP extends javax.swing.JFrame {

    /**
     * Creates new form SiswaSindy
     */
    
    private boolean[] bulan = new boolean[12]; 
    int total = 0;
    public SPP() {
    initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        North = new javax.swing.JPanel();
        LabelJudul = new javax.swing.JLabel();
        LabelNama = new javax.swing.JLabel();
        inputbayar = new javax.swing.JTextField();
        LabelBayar = new javax.swing.JLabel();
        inputnama = new javax.swing.JTextField();
        LabelJumlahSpp = new javax.swing.JLabel();
        jumlahspp = new javax.swing.JTextField();
        LabelInfo = new javax.swing.JLabel();
        LabelGaris1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        LabelGaris2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        riwayat = new javax.swing.JTextArea();
        Riwayat = new javax.swing.JLabel();
        totalpembayaran = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        South = new javax.swing.JPanel();
        keluar = new javax.swing.JButton();
        cekstatus = new javax.swing.JButton();
        bayar = new javax.swing.JButton();
        menghitungpembayaran = new javax.swing.JButton();
        East = new javax.swing.JPanel();
        Center = new javax.swing.JPanel();
        Januari = new javax.swing.JCheckBox();
        Februari = new javax.swing.JCheckBox();
        Maret = new javax.swing.JCheckBox();
        April = new javax.swing.JCheckBox();
        Mei = new javax.swing.JCheckBox();
        Juni = new javax.swing.JCheckBox();
        Juli = new javax.swing.JCheckBox();
        Agustus = new javax.swing.JCheckBox();
        September = new javax.swing.JCheckBox();
        Oktober = new javax.swing.JCheckBox();
        November = new javax.swing.JCheckBox();
        Desember = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        North.setBackground(new java.awt.Color(153, 204, 255));
        North.setMinimumSize(new java.awt.Dimension(681, 100));
        North.setPreferredSize(new java.awt.Dimension(650, 300));
        North.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelJudul.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        LabelJudul.setText("PEMBAYARAN SPP SMK NEGERI 1 LABANG");
        North.add(LabelJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 370, -1));

        LabelNama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelNama.setText("Nama Siswa :");
        North.add(LabelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, -1));
        North.add(inputbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 180, -1));

        LabelBayar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelBayar.setText("Bayar :");
        North.add(LabelBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 20));
        North.add(inputnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 180, -1));

        LabelJumlahSpp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelJumlahSpp.setText("Jumlah SPP :");
        North.add(LabelJumlahSpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 20));
        North.add(jumlahspp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 180, -1));

        LabelInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        North.add(LabelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 170, -1));

        LabelGaris1.setText("=================================================================================");
        North.add(LabelGaris1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 30));

        jLabel3.setText("Jalan Raya, Labang Dajah, Labang, Bangkalan Regency");
        North.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        Status.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Status.setText("Status :");
        North.add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        LabelGaris2.setText("=================================================================================");
        North.add(LabelGaris2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 650, 20));

        riwayat.setEditable(false);
        riwayat.setColumns(20);
        riwayat.setRows(5);
        jScrollPane1.setViewportView(riwayat);

        North.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 300, 110));

        Riwayat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Riwayat.setText("Riwayat Pembayaran :");
        North.add(Riwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));
        North.add(totalpembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 180, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("total :");
        North.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\PRAKTIKUM PEMVIS D\\CODINGAN\\MODUL1\\Picture1.png")); // NOI18N
        North.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\PRAKTIKUM PEMVIS D\\CODINGAN\\MODUL1\\Picture2.png")); // NOI18N
        North.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel5.setText(" East Java 69163");
        North.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        getContentPane().add(North, java.awt.BorderLayout.PAGE_START);

        South.setBackground(new java.awt.Color(153, 204, 255));

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        South.add(keluar);

        cekstatus.setText("Cek Status");
        cekstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekstatusActionPerformed(evt);
            }
        });
        South.add(cekstatus);

        bayar.setText("Bayar");
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        South.add(bayar);

        menghitungpembayaran.setText("Hitung");
        menghitungpembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menghitungpembayaranActionPerformed(evt);
            }
        });
        South.add(menghitungpembayaran);

        getContentPane().add(South, java.awt.BorderLayout.PAGE_END);

        East.setBackground(new java.awt.Color(255, 255, 204));
        East.setLayout(new javax.swing.BoxLayout(East, javax.swing.BoxLayout.PAGE_AXIS));
        getContentPane().add(East, java.awt.BorderLayout.LINE_END);

        Center.setBackground(new java.awt.Color(102, 204, 255));
        Center.setPreferredSize(new java.awt.Dimension(336, 100));
        Center.setLayout(new java.awt.GridLayout(3, 4));

        Januari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Januari.setText("Januari");
        Center.add(Januari);

        Februari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Februari.setText("Februari");
        Center.add(Februari);

        Maret.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Maret.setText("Maret");
        Center.add(Maret);

        April.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        April.setText("April");
        April.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AprilActionPerformed(evt);
            }
        });
        Center.add(April);

        Mei.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Mei.setText("Mei");
        Center.add(Mei);

        Juni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Juni.setText("Juni");
        Center.add(Juni);

        Juli.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Juli.setText("Juli");
        Juli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JuliActionPerformed(evt);
            }
        });
        Center.add(Juli);

        Agustus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Agustus.setText("Agustus");
        Center.add(Agustus);

        September.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        September.setText("September");
        Center.add(September);

        Oktober.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Oktober.setText("Oktober");
        Center.add(Oktober);

        November.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        November.setText("November");
        Center.add(November);

        Desember.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Desember.setText("Desember");
        Center.add(Desember);

        getContentPane().add(Center, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JuliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JuliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JuliActionPerformed

    private void menghitungpembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menghitungpembayaranActionPerformed
        // TODO add your handling code here:
        int spp = Integer.parseInt(jumlahspp.getText()); // Jumlah SPP per bulan
        
        if (Januari.isSelected() && !bulan[0]) total += spp;
        if (Februari.isSelected() && !bulan[1]) total += spp;
        if (Maret.isSelected() && !bulan[2]) total += spp;
        if (April.isSelected() && !bulan[3]) total += spp; 
        if (Mei.isSelected() && !bulan[4]) total += spp;
        if (Juni.isSelected() && !bulan[5]) total += spp;
        if (Juli.isSelected() && !bulan[6]) total += spp;
        if (Agustus.isSelected() && !bulan[7]) total += spp;
        if (September.isSelected() && !bulan[8]) total += spp;
        if (Oktober.isSelected() && !bulan[9]) total += spp;
        if (November.isSelected() && !bulan[10]) total += spp;
        if (Desember.isSelected() && !bulan[11]) total += spp;
        
        // hasil total pembayaran
        totalpembayaran.setText(String.valueOf(total));     
        
        JOptionPane.showMessageDialog(this, "Total Pembayaran: Rp " + total);
    }//GEN-LAST:event_menghitungpembayaranActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
            // TODO add your handling code here:
             
        
        
       String NamaSiswa = inputnama.getText();

// Validasi atau parsing input yang diharapkan berbentuk angka (misal: jumlah pembayaran)
double jumlah;
try {
    jumlah = Double.parseDouble(inputbayar.getText());
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Masukkan jumlah pembayaran yang valid.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
    return; 
}

// Simpan status awal dari bulan untuk rollback jika pembayaran kurang
boolean[] bulanAwal = bulan.clone(); // Menyimpan status awal bulan sebelum pembayaran

StringBuilder InfromasiPembayaran = new StringBuilder("Pembayaran oleh " + NamaSiswa + " untuk bulan: ");

// Cek tiap bulan dan tambahkan ke log pembayaran jika dipilih dan belum lunas
if (Januari.isSelected() && !bulan[0]) {
    bulan[0] = true;
    InfromasiPembayaran.append("Januari, ");
}
if (Februari.isSelected() && !bulan[1]) {
    bulan[1] = true;
    InfromasiPembayaran.append("Februari, ");
}
if (Maret.isSelected() && !bulan[2]) {
    bulan[2] = true;
    InfromasiPembayaran.append("Maret, ");
}
if (April.isSelected() && !bulan[3]) {
    bulan[3] = true;
    InfromasiPembayaran.append("April, ");
}
if (Mei.isSelected() && !bulan[4]) {
    bulan[4] = true;
    InfromasiPembayaran.append("Mei, ");
}
if (Juni.isSelected() && !bulan[5]) {
    bulan[5] = true;
    InfromasiPembayaran.append("Juni, ");
}
if (Juli.isSelected() && !bulan[6]) {
    bulan[6] = true;
    InfromasiPembayaran.append("Juli, ");
}
if (Agustus.isSelected() && !bulan[7]) {
    bulan[7] = true;
    InfromasiPembayaran.append("Agustus, ");
}
if (September.isSelected() && !bulan[8]) {
    bulan[8] = true;
    InfromasiPembayaran.append("September, ");
}
if (Oktober.isSelected() && !bulan[9]) {
    bulan[9] = true;
    InfromasiPembayaran.append("Oktober, ");
}
if (November.isSelected() && !bulan[10]) {
    bulan[10] = true;
    InfromasiPembayaran.append("November, ");
}
if (Desember.isSelected() && !bulan[11]) {
    bulan[11] = true;
    InfromasiPembayaran.append("Desember, ");
}

// Cek apakah jumlah pembayaran cukup atau berlebihan
if (jumlah < total) {
    // Jika pembayaran kurang, kembalikan status bulan ke kondisi awal
    bulan = bulanAwal; // Rollback ke status bulan sebelum pembayaran
    JOptionPane.showMessageDialog(this, "Uang pembayaran tidak cukup! Total Anda : " + total, "PERINGATAN", JOptionPane.ERROR_MESSAGE);
    return;
} else if (jumlah > total) {
    JOptionPane.showMessageDialog(this, "Masukkan uang pas! Total Anda : " + total, "PERINGATAN", JOptionPane.WARNING_MESSAGE);
    return;
}

// Tampilkan log pembayaran di area riwayat pembayaran 
riwayat.append(InfromasiPembayaran.toString() + "\n");
JOptionPane.showMessageDialog(this, "Pembayaran berhasil diproses.", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);

// CekStatusActionPerformed(evt);
    }//GEN-LAST:event_bayarActionPerformed

    private void cekstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekstatusActionPerformed
        // TODO add your handling code here:
        boolean cekstatus = false;
        StringBuilder status = new StringBuilder("Bulan yang belum dibayar : ");
        // status.setLength(0);
        
        if (!bulan[0]) {
            cekstatus = true;
            status.append("Januari, ");
        }
        if (!bulan[1]) {
            cekstatus = true;
            status.append("Februari, ");
        }
        if (!bulan[2]) {
            cekstatus = true;
            status.append("Maret, ");
        }
        if (!bulan[3]) {
            cekstatus = true;
            status.append("April, ");
        }
        if (!bulan[4]) {
            cekstatus = true;
            status.append("Mei, ");
        }
        if (!bulan[5]) {
            cekstatus = true;
            status.append("Juni, ");
        }
        if (!bulan[6]) {
            cekstatus = true;
            status.append("Juli, ");
        }
        if (!bulan[7]) {
            cekstatus = true;
            status.append("Agustus, ");
        }
        if (!bulan[8]) {
            cekstatus = true;
            status.append("September, ");
        }
        if (!bulan[9]) {
            cekstatus = true;
            status.append("Oktober, ");
        }
        if (!bulan[10]) {
            cekstatus = true;
            status.append("November, ");
        }
        if (!bulan[11]) {
            cekstatus = true;
            status.append("Desember, ");
        }
        
        if (cekstatus) {
            Status.setText("Status : Menunggak");
            JOptionPane.showMessageDialog(this, status.toString());
        } else {
            Status.setText("Status : Lunas");
            JOptionPane.showMessageDialog(this, "Pembayaran Anda Sudah LUNAS", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cekstatusActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void AprilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AprilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AprilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SPP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Agustus;
    private javax.swing.JCheckBox April;
    private javax.swing.JPanel Center;
    private javax.swing.JCheckBox Desember;
    private javax.swing.JPanel East;
    private javax.swing.JCheckBox Februari;
    private javax.swing.JCheckBox Januari;
    private javax.swing.JCheckBox Juli;
    private javax.swing.JCheckBox Juni;
    private javax.swing.JLabel LabelBayar;
    private javax.swing.JLabel LabelGaris1;
    private javax.swing.JLabel LabelGaris2;
    private javax.swing.JLabel LabelInfo;
    private javax.swing.JLabel LabelJudul;
    private javax.swing.JLabel LabelJumlahSpp;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JCheckBox Maret;
    private javax.swing.JCheckBox Mei;
    private javax.swing.JPanel North;
    private javax.swing.JCheckBox November;
    private javax.swing.JCheckBox Oktober;
    private javax.swing.JLabel Riwayat;
    private javax.swing.JCheckBox September;
    private javax.swing.JPanel South;
    private javax.swing.JLabel Status;
    private javax.swing.JButton bayar;
    private javax.swing.JButton cekstatus;
    private javax.swing.JTextField inputbayar;
    private javax.swing.JTextField inputnama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahspp;
    private javax.swing.JButton keluar;
    private javax.swing.JButton menghitungpembayaran;
    private javax.swing.JTextArea riwayat;
    private javax.swing.JTextField totalpembayaran;
    // End of variables declaration//GEN-END:variables
}
