/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.modul3;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class APotek extends javax.swing.JFrame {

     // Buat list untuk menyimpan daftar obat yang dibeli
    private ArrayList<String> daftarObat = new ArrayList<>();
    private int totalHarga = 0;
    /**
     * Creates new form APotek
     */
    public APotek() {
        initComponents();
    }
private void addObat(String namaObat, int hargaObat) {
        daftarObat.add(namaObat + " - Rp " + hargaObat);
        totalHarga += hargaObat;
        JOptionPane.showMessageDialog(this, namaObat + " berhasil ditambahkan ke daftar belanja!", "Pembelian Berhasil", JOptionPane.INFORMATION_MESSAGE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        Buttonbeli = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Paracetamol = new javax.swing.JRadioButton();
        Amoxicillin = new javax.swing.JRadioButton();
        Dexamethasone = new javax.swing.JRadioButton();
        Ranitidine = new javax.swing.JRadioButton();
        Inhaler = new javax.swing.JRadioButton();
        Ibuprofen = new javax.swing.JRadioButton();
        Loperamide = new javax.swing.JRadioButton();
        antasida = new javax.swing.JRadioButton();
        Metformin = new javax.swing.JRadioButton();
        Cetirizine = new javax.swing.JRadioButton();
        ButtondetailCetirizine = new javax.swing.JButton();
        ButtondetailMetformin = new javax.swing.JButton();
        ButtondetailLoperamide = new javax.swing.JButton();
        ButtondetailAntasida = new javax.swing.JButton();
        ButtondetailIbuprofen = new javax.swing.JButton();
        ButtondetailDexamethasone = new javax.swing.JButton();
        ButtondetailAmoxicillin = new javax.swing.JButton();
        ButtondetailInhaler = new javax.swing.JButton();
        ButtondetailRanitidine = new javax.swing.JButton();
        Buttonparacetamol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(503, 300));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setMinimumSize(new java.awt.Dimension(143, 143));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\PRAKTIKUM PEMVIS D\\icon\\pngtree-pharmacy-logo-vector-template-png-image_5230126.png")); // NOI18N
        jPanel2.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("APOTEK MINI");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jButton1.setText("keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        hapus.setText("hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel3.add(hapus);

        Buttonbeli.setText("Membeli");
        Buttonbeli.setMaximumSize(new java.awt.Dimension(75, 75));
        Buttonbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonbeliActionPerformed(evt);
            }
        });
        jPanel3.add(Buttonbeli);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(302, 202));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        Paracetamol.setText("Paracetamol");
        Paracetamol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParacetamolActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(Paracetamol, gridBagConstraints);

        Amoxicillin.setText("Amoxicillin");
        Amoxicillin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmoxicillinActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel1.add(Amoxicillin, gridBagConstraints);

        Dexamethasone.setText("Dexamethasone");
        Dexamethasone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DexamethasoneActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        jPanel1.add(Dexamethasone, gridBagConstraints);

        Ranitidine.setText("Ranitidine");
        Ranitidine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RanitidineActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel1.add(Ranitidine, gridBagConstraints);

        Inhaler.setText("Salbutamol (Inhaler)");
        Inhaler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InhalerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        jPanel1.add(Inhaler, gridBagConstraints);

        Ibuprofen.setText("Ibuprofen");
        Ibuprofen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IbuprofenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel1.add(Ibuprofen, gridBagConstraints);

        Loperamide.setText("Loperamide");
        Loperamide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoperamideActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        jPanel1.add(Loperamide, gridBagConstraints);

        antasida.setText(" Antasida");
        antasida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antasidaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        jPanel1.add(antasida, gridBagConstraints);

        Metformin.setText("Metformin");
        Metformin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MetforminActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        jPanel1.add(Metformin, gridBagConstraints);

        Cetirizine.setText("Cetirizine");
        Cetirizine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetirizineActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        jPanel1.add(Cetirizine, gridBagConstraints);

        ButtondetailCetirizine.setBackground(new java.awt.Color(102, 255, 204));
        ButtondetailCetirizine.setIcon(new javax.swing.ImageIcon("D:\\PRAKTIKUM PEMVIS D\\icon\\CETIRIZINE-HCL-1.png")); // NOI18N
        ButtondetailCetirizine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtondetailCetirizineActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 16;
        jPanel1.add(ButtondetailCetirizine, gridBagConstraints);

        ButtondetailMetformin.setBackground(new java.awt.Color(102, 255, 204));
        ButtondetailMetformin.setIcon(new javax.swing.ImageIcon("D:\\PRAKTIKUM PEMVIS D\\icon\\farmaku_metformin-500-mg-tablet-hexp-01.jpg")); // NOI18N
        ButtondetailMetformin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtondetailMetforminActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.ipady = 11;
        jPanel1.add(ButtondetailMetformin, gridBagConstraints);

        ButtondetailLoperamide.setBackground(new java.awt.Color(51, 255, 204));
        ButtondetailLoperamide.setIcon(new javax.swing.ImageIcon("D:\\PRAKTIKUM PEMVIS D\\icon\\farmaku_imodium-2-mg-tablet-01.jpg")); // NOI18N
        ButtondetailLoperamide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtondetailLoperamideActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 13;
        jPanel1.add(ButtondetailLoperamide, gridBagConstraints);

        ButtondetailAntasida.setBackground(new java.awt.Color(102, 255, 204));
        ButtondetailAntasida.setIcon(new javax.swing.ImageIcon("D:\\PRAKTIKUM PEMVIS D\\icon\\e887a0a82b97a0456a468a376e1705c8.jpg")); // NOI18N
        ButtondetailAntasida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtondetailAntasidaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 11;
        jPanel1.add(ButtondetailAntasida, gridBagConstraints);

        ButtondetailIbuprofen.setBackground(new java.awt.Color(51, 255, 204));
        ButtondetailIbuprofen.setIcon(new javax.swing.ImageIcon("D:\\PRAKTIKUM PEMVIS D\\icon\\GUEST_1c8e9085-a588-43b5-859d-a6d1ac691347.png")); // NOI18N
        ButtondetailIbuprofen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtondetailIbuprofenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 11;
        jPanel1.add(ButtondetailIbuprofen, gridBagConstraints);

        ButtondetailDexamethasone.setBackground(new java.awt.Color(102, 255, 204));
        ButtondetailDexamethasone.setIcon(new javax.swing.ImageIcon("D:\\PRAKTIKUM PEMVIS D\\icon\\Dexamethasone-0.5-Mg-Strip-10-Tablet-NEW-2_749x749.png")); // NOI18N
        ButtondetailDexamethasone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtondetailDexamethasoneActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.ipady = 11;
        jPanel1.add(ButtondetailDexamethasone, gridBagConstraints);

        ButtondetailAmoxicillin.setBackground(new java.awt.Color(51, 255, 204));
        ButtondetailAmoxicillin.setIcon(new javax.swing.ImageIcon("D:\\PRAKTIKUM PEMVIS D\\icon\\61EBB28BAAEE65.jpg")); // NOI18N
        ButtondetailAmoxicillin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtondetailAmoxicillinActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.ipady = 9;
        jPanel1.add(ButtondetailAmoxicillin, gridBagConstraints);

        ButtondetailInhaler.setBackground(new java.awt.Color(102, 255, 204));
        ButtondetailInhaler.setIcon(new javax.swing.ImageIcon("D:\\PRAKTIKUM PEMVIS D\\icon\\Ventolin Inhaler6002PPS0.jpeg")); // NOI18N
        ButtondetailInhaler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtondetailInhalerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weighty = 0.2;
        jPanel1.add(ButtondetailInhaler, gridBagConstraints);

        ButtondetailRanitidine.setBackground(new java.awt.Color(153, 255, 204));
        ButtondetailRanitidine.setIcon(new javax.swing.ImageIcon("D:\\PRAKTIKUM PEMVIS D\\icon\\90b15a1892df4878e2fc24495c3c891b.jpg")); // NOI18N
        ButtondetailRanitidine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtondetailRanitidineActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 13;
        jPanel1.add(ButtondetailRanitidine, gridBagConstraints);

        Buttonparacetamol.setBackground(new java.awt.Color(51, 255, 204));
        Buttonparacetamol.setIcon(new javax.swing.ImageIcon("D:\\PRAKTIKUM PEMVIS D\\icon\\paracetamol generik.jpg")); // NOI18N
        Buttonparacetamol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonparacetamolActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 4;
        jPanel1.add(Buttonparacetamol, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonparacetamolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonparacetamolActionPerformed
        // TODO add your handling code here:
          String deskripsi = "Paracetamol: Digunakan untuk mengurangi demam dan nyeri ringan hingga sedang.";
        String harga = "Harga: Rp 10.000";
        JOptionPane.showMessageDialog(this, deskripsi + "\n" + harga, "Detail Paracetamol", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ButtonparacetamolActionPerformed

    private void ButtondetailAmoxicillinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtondetailAmoxicillinActionPerformed
        // TODO add your handling code here:
        String deskripsi = "Amoxicillin: Antibiotik untuk mengobati infeksi bakteri.";
        String harga = "Harga: Rp 15.000";
        JOptionPane.showMessageDialog(this, deskripsi + "\n" + harga, "Detail Amoxicillin", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ButtondetailAmoxicillinActionPerformed

    private void ParacetamolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParacetamolActionPerformed
        // TODO add your handling code here:
        addObat("Paracetamol", 10000);
        
    }//GEN-LAST:event_ParacetamolActionPerformed

    private void AmoxicillinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmoxicillinActionPerformed
        // TODO add your handling code here:
         addObat("Amoxicillin", 15000);
    }//GEN-LAST:event_AmoxicillinActionPerformed

    private void IbuprofenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IbuprofenActionPerformed
        // TODO add your handling code here:
         addObat("Ibuprofen", 12000);
    }//GEN-LAST:event_IbuprofenActionPerformed

    private void ButtondetailIbuprofenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtondetailIbuprofenActionPerformed
        // TODO add your handling code here:
         String deskripsi = "Ibuprofen: Obat anti-inflamasi nonsteroid untuk mengurangi rasa sakit dan peradangan.";
        String harga = "Harga: Rp 12.000";
        JOptionPane.showMessageDialog(this, deskripsi + "\n" + harga, "Detail Ibuprofen", JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_ButtondetailIbuprofenActionPerformed

    private void ButtondetailLoperamideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtondetailLoperamideActionPerformed
        // TODO add your handling code here:
        String deskripsi = "Loperamide: Obat untuk mengatasi diare.";
        String harga = "Harga: Rp 8.000";
        JOptionPane.showMessageDialog(this, deskripsi + "\n" + harga, "Detail Loperamide", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ButtondetailLoperamideActionPerformed

    private void LoperamideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoperamideActionPerformed
        // TODO add your handling code here:
         addObat("Loperamide", 8000);
    }//GEN-LAST:event_LoperamideActionPerformed

    private void ButtondetailCetirizineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtondetailCetirizineActionPerformed
        // TODO add your handling code here:
        String deskripsi = "Cetirizine: Obat antihistamin untuk mengobati alergi.";
        String harga = "Harga: Rp 7.000";
        JOptionPane.showMessageDialog(this, deskripsi + "\n" + harga, "Detail Cetirizine", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ButtondetailCetirizineActionPerformed

    private void CetirizineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetirizineActionPerformed
        // TODO add your handling code here:
        addObat("Cetirizine", 7000);
    }//GEN-LAST:event_CetirizineActionPerformed

    private void RanitidineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RanitidineActionPerformed
        // TODO add your handling code here:
         addObat("Ranitidine", 9000);
    }//GEN-LAST:event_RanitidineActionPerformed

    private void ButtondetailRanitidineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtondetailRanitidineActionPerformed
        // TODO add your handling code here:
        String deskripsi = "Ranitidine: Obat untuk mengurangi produksi asam lambung.";
        String harga = "Harga: Rp 9.000";
        JOptionPane.showMessageDialog(this, deskripsi + "\n" + harga, "Detail Ranitidine", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ButtondetailRanitidineActionPerformed

    private void InhalerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InhalerActionPerformed
        // TODO add your handling code here:
        addObat("Inhaler", 50000);
    }//GEN-LAST:event_InhalerActionPerformed

    private void ButtondetailInhalerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtondetailInhalerActionPerformed
        // TODO add your handling code here:
         String deskripsi = "Inhaler: Alat untuk mengatasi sesak napas akibat asma.";
        String harga = "Harga: Rp 50.000";
        JOptionPane.showMessageDialog(this, deskripsi + "\n" + harga, "Detail Inhaler", JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_ButtondetailInhalerActionPerformed

    private void DexamethasoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DexamethasoneActionPerformed
        // TODO add your handling code here:
        addObat("Dexamethasone", 25000);
    }//GEN-LAST:event_DexamethasoneActionPerformed

    private void ButtondetailDexamethasoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtondetailDexamethasoneActionPerformed
        // TODO add your handling code here:
         String deskripsi = "Dexamethasone: Steroid untuk mengurangi inflamasi.";
        String harga = "Harga: Rp 25.000";
        JOptionPane.showMessageDialog(this, deskripsi + "\n" + harga, "Detail Dexamethasone", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ButtondetailDexamethasoneActionPerformed

    private void antasidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antasidaActionPerformed
        // TODO add your handling code here:
         addObat("Antasida", 5000);
    }//GEN-LAST:event_antasidaActionPerformed

    private void ButtondetailAntasidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtondetailAntasidaActionPerformed
        // TODO add your handling code here:
         String deskripsi = "Antasida: Obat untuk meredakan gejala maag dan asam lambung.";
        String harga = "Harga: Rp 5.000";
        JOptionPane.showMessageDialog(this, deskripsi + "\n" + harga, "Detail Antasida", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ButtondetailAntasidaActionPerformed

    private void MetforminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MetforminActionPerformed
        // TODO add your handling code here:
          addObat("Metformin", 20000);
    }//GEN-LAST:event_MetforminActionPerformed

    private void ButtondetailMetforminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtondetailMetforminActionPerformed
        // TODO add your handling code here:
        String deskripsi = "Metformin: Obat untuk mengontrol kadar gula darah pada diabetes tipe 2.";
        String harga = "Harga: Rp 20.000";
        JOptionPane.showMessageDialog(this, deskripsi + "\n" + harga, "Detail Metformin", JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_ButtondetailMetforminActionPerformed

    private void ButtonbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonbeliActionPerformed
        // TODO add your handling code here:
          if (daftarObat.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Anda belum memilih obat!", "Pembelian Kosong", JOptionPane.WARNING_MESSAGE);
        } else {
            // Tampilkan struk
            StringBuilder struk = new StringBuilder("STRUK PEMBELIAN\n");
            struk.append("=====================\n");

            for (String item : daftarObat) {
                struk.append(item).append("\n");
            }

            struk.append("=====================\n");
            struk.append("Total Harga: Rp ").append(totalHarga).append("\n");

            JOptionPane.showMessageDialog(this, struk.toString(), "Struk Pembelian", JOptionPane.INFORMATION_MESSAGE);

            // Tampilkan opsi bayar
            int bayar = JOptionPane.showConfirmDialog(this, "Total Harga: Rp " + totalHarga + "\nApakah Anda ingin membayar sekarang?", "Pembayaran", JOptionPane.YES_NO_OPTION);

            if (bayar == JOptionPane.YES_OPTION) {
                // Tampilkan pesan pembayaran berhasil
                JOptionPane.showMessageDialog(this, "Pembayaran berhasil!\nTerima kasih telah berbelanja.", "Pembayaran Sukses", JOptionPane.INFORMATION_MESSAGE);

                // Reset daftar belanja setelah pembayaran
                daftarObat.clear();
                totalHarga = 0;
            }
        }
    }//GEN-LAST:event_ButtonbeliActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
         daftarObat.clear();
        totalHarga = 0;

        // Reset semua radio button
        Paracetamol.setSelected(false);
        Amoxicillin.setSelected(false);
        Dexamethasone.setSelected(false);
        Ranitidine.setSelected(false);
        Inhaler.setSelected(false);
        Ibuprofen.setSelected(false);
        Loperamide.setSelected(false);
        antasida.setSelected(false);
        Metformin.setSelected(false);
        Cetirizine.setSelected(false);
    }//GEN-LAST:event_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APotek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Amoxicillin;
    private javax.swing.JButton Buttonbeli;
    private javax.swing.JButton ButtondetailAmoxicillin;
    private javax.swing.JButton ButtondetailAntasida;
    private javax.swing.JButton ButtondetailCetirizine;
    private javax.swing.JButton ButtondetailDexamethasone;
    private javax.swing.JButton ButtondetailIbuprofen;
    private javax.swing.JButton ButtondetailInhaler;
    private javax.swing.JButton ButtondetailLoperamide;
    private javax.swing.JButton ButtondetailMetformin;
    private javax.swing.JButton ButtondetailRanitidine;
    private javax.swing.JButton Buttonparacetamol;
    private javax.swing.JRadioButton Cetirizine;
    private javax.swing.JRadioButton Dexamethasone;
    private javax.swing.JRadioButton Ibuprofen;
    private javax.swing.JRadioButton Inhaler;
    private javax.swing.JRadioButton Loperamide;
    private javax.swing.JRadioButton Metformin;
    private javax.swing.JRadioButton Paracetamol;
    private javax.swing.JRadioButton Ranitidine;
    private javax.swing.JRadioButton antasida;
    private javax.swing.JButton hapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
