/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.m2;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author ASUS
 */
public class rotiodanrotiboy extends javax.swing.JFrame {

    /**
     * Creates new form rotiodanrotiboy
     */
     private double totalHarga = 0;
    private int jumlahPesanan = 0;
    public rotiodanrotiboy() {
        initComponents();
        uangcash.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                penghitungan();
            }
        });
        jumlahroti.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jSeparator16 = new javax.swing.JSeparator();
        RotiO = new javax.swing.JRadioButton();
        Rotiboy = new javax.swing.JRadioButton();
        Cromboloni = new javax.swing.JRadioButton();
        RotiKopi = new javax.swing.JRadioButton();
        RotiCanai = new javax.swing.JRadioButton();
        Rotitisu = new javax.swing.JRadioButton();
        RotiBakar = new javax.swing.JRadioButton();
        RotiPrata = new javax.swing.JRadioButton();
        RotiMaryam = new javax.swing.JRadioButton();
        RotiJala = new javax.swing.JRadioButton();
        RotiTelur = new javax.swing.JRadioButton();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        notopping = new javax.swing.JRadioButton();
        strawberry = new javax.swing.JRadioButton();
        keju = new javax.swing.JRadioButton();
        cokelat = new javax.swing.JRadioButton();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        kurangiroti = new javax.swing.JButton();
        tambahroti = new javax.swing.JButton();
        jLabel117 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jumlahroti = new javax.swing.JTextField();
        jLabel118 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        hitungtotal = new javax.swing.JButton();
        uangcash = new javax.swing.JTextField();
        hasiltotal = new javax.swing.JTextField();
        jLabel80 = new javax.swing.JLabel();
        kembalian = new javax.swing.JTextField();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        Reset = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel9.setBackground(new java.awt.Color(255, 255, 204));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel3.setText("ROTI'O AND ROTI BOY");

        jPanel8.setBackground(new java.awt.Color(255, 255, 0));

        jSeparator16.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        buttonGroup1.add(RotiO);
        RotiO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RotiO.setText("Roti O");
        RotiO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotiOActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rotiboy);
        Rotiboy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Rotiboy.setText("Roti Boy");
        Rotiboy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotiboyActionPerformed(evt);
            }
        });

        buttonGroup1.add(Cromboloni);
        Cromboloni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Cromboloni.setText("Cromboloni");
        Cromboloni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CromboloniActionPerformed(evt);
            }
        });

        buttonGroup1.add(RotiKopi);
        RotiKopi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RotiKopi.setText("Roti Kopi");
        RotiKopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotiKopiActionPerformed(evt);
            }
        });

        buttonGroup1.add(RotiCanai);
        RotiCanai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RotiCanai.setText("Roti Canai");
        RotiCanai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotiCanaiActionPerformed(evt);
            }
        });

        buttonGroup1.add(Rotitisu);
        Rotitisu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Rotitisu.setText("Roti Tisu");
        Rotitisu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotitisuActionPerformed(evt);
            }
        });

        buttonGroup1.add(RotiBakar);
        RotiBakar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RotiBakar.setText("Roti Bakar");
        RotiBakar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotiBakarActionPerformed(evt);
            }
        });

        buttonGroup1.add(RotiPrata);
        RotiPrata.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RotiPrata.setText("Roti Prata");
        RotiPrata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotiPrataActionPerformed(evt);
            }
        });

        buttonGroup1.add(RotiMaryam);
        RotiMaryam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RotiMaryam.setText("Roti Maryam");
        RotiMaryam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotiMaryamActionPerformed(evt);
            }
        });

        buttonGroup1.add(RotiJala);
        RotiJala.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RotiJala.setText("Roti Jala");
        RotiJala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotiJalaActionPerformed(evt);
            }
        });

        buttonGroup1.add(RotiTelur);
        RotiTelur.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RotiTelur.setText("Roti Telur");
        RotiTelur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RotiTelurActionPerformed(evt);
            }
        });

        jLabel99.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel99.setText("Menu - menu Roti");

        jLabel100.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel100.setText("Menu Utama");

        jLabel101.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel101.setText("Topping");

        jLabel102.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel102.setText("(Rp18.000) ");

        jLabel103.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel103.setText("(Rp18.000 )");

        jLabel104.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel104.setText("Rp16.000");

        jLabel105.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel105.setText("(Rp20.000)");

        jLabel106.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel106.setText("(Rp25.000)");

        jLabel107.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel107.setText("(Rp14.000)");

        jLabel108.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel108.setText("(Rp19.000)");

        jLabel109.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel109.setText("(Rp16.000)");

        jLabel110.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel110.setText("(Rp20.000)");

        jLabel111.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel111.setText("(Rp10.000)");

        jLabel112.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel112.setText("(Rp13.000)");

        buttonGroup2.add(notopping);
        notopping.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        notopping.setText("No Topping");
        notopping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notoppingActionPerformed(evt);
            }
        });

        buttonGroup2.add(strawberry);
        strawberry.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        strawberry.setText("Strawbery");
        strawberry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strawberryActionPerformed(evt);
            }
        });

        buttonGroup2.add(keju);
        keju.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        keju.setText("keju");
        keju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kejuActionPerformed(evt);
            }
        });

        buttonGroup2.add(cokelat);
        cokelat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cokelat.setText("Cokelat");
        cokelat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cokelatActionPerformed(evt);
            }
        });

        jLabel113.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel113.setText("(0)");

        jLabel114.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel114.setText("(Rp6.000)");

        jLabel115.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel115.setText("(Rp5.000)");

        jLabel116.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel116.setText("(Rp5.000)");

        kurangiroti.setText("kurang");
        kurangiroti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangirotiActionPerformed(evt);
            }
        });

        tambahroti.setText("tambah");
        tambahroti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahrotiActionPerformed(evt);
            }
        });

        jLabel117.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel117.setText("jumlah dan cash");

        jumlahroti.setEditable(false);
        jumlahroti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahrotiActionPerformed(evt);
            }
        });

        jLabel118.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel118.setText("Total dan kembalian");

        hitungtotal.setText("Total");
        hitungtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungtotalActionPerformed(evt);
            }
        });

        uangcash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uangcashActionPerformed(evt);
            }
        });

        hasiltotal.setEditable(false);
        hasiltotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasiltotalActionPerformed(evt);
            }
        });

        jLabel80.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel80.setText("total");

        kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianActionPerformed(evt);
            }
        });

        jLabel81.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel81.setText("kembalian");

        jLabel82.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel82.setText("uang cash");

        Reset.setText("reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        batal.setText("batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("Diskon");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("jika pembelian melebihi ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Rp100.000");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Mendapatkan diskon 5%");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel118)
                            .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(notopping)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel113)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel114, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(strawberry))
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel115)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel116))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(keju)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cokelat))))
                            .addComponent(jLabel117)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(kurangiroti)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jumlahroti, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tambahroti)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel82)
                                    .addComponent(uangcash, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(hitungtotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hasiltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel80))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel81)
                                    .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel101, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filler5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(Reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel100)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(Cromboloni)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Rotitisu))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RotiKopi)
                                            .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel102)
                                                    .addComponent(jLabel103))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel106, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(RotiBakar, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel105, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RotiCanai)
                                            .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel104)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel110))
                                            .addComponent(RotiPrata))))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RotiJala, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RotiMaryam)
                                    .addComponent(RotiTelur, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel107)
                                            .addComponent(jLabel109)))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel108))))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel99)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(32, 32, 32)
                        .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RotiO)
                            .addComponent(Rotiboy)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel111)
                                    .addComponent(jLabel112))))
                        .addGap(103, 103, 103))))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(batal)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(282, 282, 282))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel100)
                                .addGap(12, 12, 12)
                                .addComponent(RotiO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel111)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Rotiboy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel112))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel99)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel102)
                                            .addComponent(jLabel106)
                                            .addComponent(jLabel107))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(RotiKopi)
                                                .addGap(1, 1, 1)
                                                .addComponent(jLabel103))
                                            .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(RotiBakar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(2, 2, 2)
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel105)
                                                    .addComponent(jLabel108)))
                                            .addComponent(RotiJala, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(RotiCanai)
                                            .addComponent(RotiPrata)
                                            .addComponent(RotiTelur))
                                        .addGap(3, 3, 3)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel104)
                                            .addComponent(jLabel110)
                                            .addComponent(jLabel109)))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Cromboloni)
                                            .addComponent(Rotitisu)
                                            .addComponent(RotiMaryam))
                                        .addGap(96, 96, 96)))))))
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel101)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(notopping)
                            .addComponent(strawberry)
                            .addComponent(keju)
                            .addComponent(cokelat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel113)
                                .addComponent(jLabel116))
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel114)
                                .addComponent(jLabel115)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel117)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(kurangiroti)
                                    .addComponent(tambahroti)
                                    .addComponent(jumlahroti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uangcash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel118))
                            .addComponent(jLabel82))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel80)
                            .addComponent(jLabel81))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hitungtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hasiltotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reset)
                    .addComponent(batal))
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\PRAKTIKUM PEMVIS D\\CODINGAN\\MODUL2\\rotiby-removebg-previe.png")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\PRAKTIKUM PEMVIS D\\CODINGAN\\MODUL2\\3512O_logo13.png")); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel119)
                    .addGap(299, 299, 299)
                    .addComponent(jLabel120, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(129, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel119, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel120, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGap(463, 463, 463)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void penghitungan() {
        try {
            double uangmasuk = Double.parseDouble(uangcash.getText());
            double kembaliann = uangmasuk - totalHarga;
            if (kembaliann >= 0) {
                kembalian.setText(String.valueOf(kembaliann));
            } else {
                kembalian.setText("Uang Tidak Cukup");
            }
        } catch (NumberFormatException e) {
            kembalian.setText("Input Tidak Sesuai");
        }
}

    private void CromboloniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CromboloniActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CromboloniActionPerformed

    private void RotiTelurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotiTelurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RotiTelurActionPerformed

    private void jumlahrotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahrotiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahrotiActionPerformed

    private void RotitisuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotitisuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RotitisuActionPerformed

    private void RotiMaryamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotiMaryamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RotiMaryamActionPerformed

    private void RotiOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotiOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RotiOActionPerformed

    private void RotiKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotiKopiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RotiKopiActionPerformed

    private void RotiCanaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotiCanaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RotiCanaiActionPerformed

    private void RotiBakarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotiBakarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RotiBakarActionPerformed

    private void RotiPrataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotiPrataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RotiPrataActionPerformed

    private void RotiJalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotiJalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RotiJalaActionPerformed

    private void RotiboyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotiboyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RotiboyActionPerformed

    private void notoppingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notoppingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notoppingActionPerformed

    private void strawberryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawberryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strawberryActionPerformed

    private void kejuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kejuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kejuActionPerformed

    private void cokelatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cokelatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cokelatActionPerformed

    private void kurangirotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangirotiActionPerformed
        // TODO add your handling code here:
          if (jumlahPesanan > 0) {
        jumlahPesanan--;
        jumlahroti.setText(String.valueOf(jumlahPesanan));
    }
    }//GEN-LAST:event_kurangirotiActionPerformed

    private void tambahrotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahrotiActionPerformed
        // TODO add your handling code here:
        jumlahPesanan++;
        jumlahroti.setText(String.valueOf(jumlahPesanan));
    }//GEN-LAST:event_tambahrotiActionPerformed

    private void uangcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangcashActionPerformed
        // TODO add your handling code here:
     
   
    
          
    }//GEN-LAST:event_uangcashActionPerformed

    private void hitungtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungtotalActionPerformed
        // TODO add your handling code here:
        if (buttonGroup1.getSelection() == null || buttonGroup2.getSelection() == null) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Silakan pilih menu roti dan topping terlebih dahulu!",
            "Peringatan",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
        return;
        }
         double menu = 0;
    if (RotiO.isSelected()) menu = 10000;
    else if (Rotiboy.isSelected()) menu = 13000;
    else if (Cromboloni.isSelected()) menu = 18000;
    else if (RotiKopi.isSelected()) menu = 18000;
    else if (RotiCanai.isSelected()) menu = 16000;
    else if (Rotitisu.isSelected()) menu = 25000;
    
    double topping = 0;
    if (strawberry.isSelected()) topping = 6000; 
    else if (keju.isSelected()) topping = 5000; 
    else if (cokelat.isSelected()) topping = 5000; 
    else if (notopping.isSelected()) topping = 0; 
    totalHarga = jumlahPesanan*(menu + topping);
    if (totalHarga >= 100000) {
        totalHarga = totalHarga * 0.95; 
    }
    
    hasiltotal.setText(String.format("Rp %.2f", totalHarga));
     

    }//GEN-LAST:event_hitungtotalActionPerformed

    private void hasiltotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasiltotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasiltotalActionPerformed

    private void kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembalianActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_batalActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        buttonGroup1.clearSelection();
    buttonGroup2.clearSelection();
    jumlahPesanan = 0;
    jumlahroti.setText("0");
    hasiltotal.setText("");
    uangcash.setText("");
    kembalian.setText("");
    totalHarga = 0;
    }//GEN-LAST:event_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rotiodanrotiboy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rotiodanrotiboy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rotiodanrotiboy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rotiodanrotiboy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rotiodanrotiboy().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Cromboloni;
    private javax.swing.JButton Reset;
    private javax.swing.JRadioButton RotiBakar;
    private javax.swing.JRadioButton RotiCanai;
    private javax.swing.JRadioButton RotiJala;
    private javax.swing.JRadioButton RotiKopi;
    private javax.swing.JRadioButton RotiMaryam;
    private javax.swing.JRadioButton RotiO;
    private javax.swing.JRadioButton RotiPrata;
    private javax.swing.JRadioButton RotiTelur;
    private javax.swing.JRadioButton Rotiboy;
    private javax.swing.JRadioButton Rotitisu;
    private javax.swing.JButton batal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton cokelat;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JTextField hasiltotal;
    private javax.swing.JButton hitungtotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jumlahroti;
    private javax.swing.JRadioButton keju;
    private javax.swing.JTextField kembalian;
    private javax.swing.JButton kurangiroti;
    private javax.swing.JRadioButton notopping;
    private javax.swing.JRadioButton strawberry;
    private javax.swing.JButton tambahroti;
    private javax.swing.JTextField uangcash;
    // End of variables declaration//GEN-END:variables
}
